import type { Metadata } from 'next';
import { openSans } from './fonts';
import './globals.css';
import UIProvider from '@/components/providers/ui-provider';
import AuthProvider from '@/components/providers/auth-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${openSans.variable}  antialiased`}>
        <AuthProvider>
          <UIProvider>
            <main className="page">{children}</main>
          </UIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
